{{- if .Values.backend.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rag-app.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rag-app.backendServiceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rag-app.fullname" . }}-backend
{{- end }}
