{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rag-app.backendServiceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
