{{- if .Values.dcgm }}
{{- if .Values.dcgm.serviceMonitor }}
{{- if .Values.dcgm.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rag-app.fullname" . }}-dcgm
  namespace: {{ .Values.dcgm.serviceMonitor.namespace | default "monitoring" }}
  labels:
    release: {{ .Values.dcgm.serviceMonitor.release | default "kube-prometheus-stack" }}
spec:
  endpoints:
  - port: {{ .Values.dcgm.serviceMonitor.portName | default "metrics" }}
    path: /metrics
    interval: {{ .Values.dcgm.serviceMonitor.interval | default "15s" }}
  namespaceSelector:
    matchNames:
    - {{ .Values.dcgm.serviceMonitor.targetNamespace | default "gpu-operator" }}
  selector:
    matchLabels:
      {{- toYaml .Values.dcgm.serviceMonitor.selector | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
