apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-app.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "rag-app.fullname" . }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
