apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-app.fullname" . }}-vllm
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "rag-app.fullname" . }}-vllm
  ports:
    - protocol: TCP
      port: {{ .Values.vllm.service.port }}
      targetPort: {{ .Values.vllm.service.port }}
