apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rag-app-rag-app-qdrant
  namespace: rag-app
spec:
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        storageClassName: standard-rwo
