apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: rag-app
    releaseName: rag-app
    version: 0.1.0
    valuesFile: values.yaml

patches:
  - path: rayservice-gpu.yaml
