apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-app

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: rag-app
    releaseName: rag-app
    version: 0.1.0
    valuesFile: ../../helm/rag-app/values.yaml
